//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinematheatre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<int> IdDirector { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Old { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Director Director { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
