//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinematheatre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<int> IdFilm { get; set; }
        public Nullable<int> IdCinemaPlace { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual CinemaPlace CinemaPlace { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Film Film { get; set; }
    }
}
